name: Run Linting (ESLint and Prettier)
run-name: ${{ github.actor }} is testing out GitHub Actions ğŸš€
on: pull_request
jobs:
  Run-eslint-prettier:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
